version: '3.8'

services:
  front-envoy:
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      - web

  web:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
