name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for Google Workload Identity Federation

env:
  PROJECT_ID: imrenagicom
  SERVICE_NAME: googlecodelabs
  REGION: asia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Workload Identity Federation or supply Service Account Key
      # Refer: https://github.com/google-github-actions/auth
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      # Automatically builds the container from the source and deploys it.
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: .
